import './main.scss';
import type { Metadata } from 'next';
import { Header, Footer } from '../widgets';
import { ReactNode } from 'react';

export const metadata: Metadata = {
	title: 'Next Layout',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
	return (
		<html lang="ru">
			<body>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
